### ISSUE TITLE
review lesson 5 dragn drop

### ISSUE THREAD

**Issue by alexey100196** [Chikintos/teymaxCourseLessons#1]
1) вынести js в отдельный файл и его подключить в html
2) var не использовать, напиши сюда разницу между  var let const
3) не надо вешать на событие load на window -
алгоритм:
1 определить элемент с которым будешь взаимодействовать
2 при зажатии мыши на этом элементе  mousedown срабатывает событие на dom mousemove - document.addEventListener('mousemove', fn - функция, которая меняет page.x page.y у элемента );
3 при событии на элементе mouseup делаешь у dom removeEventListener -    document.removeEventListener('mousemove', listener - твоя функция которую ты использовал выше (fn - функция, которая меняет page.x page.y у элемента) - вот эта );

**Comment by Chikintos** [comment]
2. var- переменные имеют глобальную и локальную область видимости и может объявляться более одного раз 
   let - переменные имеют только блочную область видимости и может объявляться более одного раз 
   const - может объявляться только один раз
[html.txt](https://github.com/Chikintos/teymaxCourseLessons/files/7615298/html.txt)
[skript.txt](https://github.com/Chikintos/teymaxCourseLessons/files/7615299/skript.txt)
