### ISSUE TITLE
review lesson-6

### ISSUE THREAD

**Issue by alexey100196** [Chikintos/teymaxCourseLessons#3]
работу я могу защитать она выполнена на 50% но лучше будет если доделаешь
1) основное, у тебя не хватает функционала, при повторном клике на активный элементы все должно вернутся к дефолтному состоянию 
2) у тебя есть active и passive, а должен быть active subctive, что имею в виду - должно быть три категории, элемент на котором срабатывает событие, элементы которые подсвечиваются по условию нажатого элемента, и пассивные элементы которые остаются в дефолтном состоянии
3) вот тут ты меняешь где то значение переменной, или ты меняй и добавляешь новые свойства переменной? понял к чему я? 
![image](https://user-images.githubusercontent.com/25837121/143896075-52b0d531-85f4-47b2-bc9d-b6a9fd2f5ddf.png)

**Comment by Chikintos** [comment]
Вот,все готово 
[ht6.txt](https://github.com/Chikintos/teymaxCourseLessons/files/7623090/ht6.txt)
